In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Mental Health Dataset.csv')
df

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146891,8/27/2014 21:35,Male,Canada,Business,No,No,Yes,Go out Every day,Maybe,Yes,Yes,High,Yes,Maybe,No,No,Not sure
146892,8/27/2014 21:39,Male,United States,Business,No,No,No,Go out Every day,Maybe,Yes,Yes,High,Yes,Maybe,No,Maybe,Yes
146893,8/27/2014 21:45,Male,Singapore,Business,No,No,No,Go out Every day,Maybe,Yes,Yes,High,Yes,Maybe,No,No,No
146894,8/27/2014 21:54,Male,Australia,Business,No,No,Yes,Go out Every day,Maybe,Yes,Yes,High,Yes,Maybe,No,No,No
146895,8/27/2014 22:00,Male,United States,Business,No,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146896 entries, 0 to 146895
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Timestamp                146896 non-null  object
 1   Gender                   146896 non-null  object
 2   Country                  146896 non-null  object
 3   Occupation               146896 non-null  object
 4   self_employed            144054 non-null  object
 5   family_history           146896 non-null  object
 6   treatment                146895 non-null  object
 7   Days_Indoors             146895 non-null  object
 8   Growing_Stress           146895 non-null  object
 9   Changes_Habits           146895 non-null  object
 10  Mental_Health_History    146895 non-null  object
 11  Mood_Swings              146895 non-null  object
 12  Coping_Struggles         146895 non-null  object
 13  Work_Interest            146895 non-null  object
 14  Social_Weakness          146895 non-null  object
 15  mental_health_interview  146895 non-null  object
 16  care_options             146895 non-null  object
dtypes: object(17)
memory usage: 19.1+ MB

In [ ]:
df.isnull().sum()

Timestamp                     0
Gender                        0
Country                       0
Occupation                    0
self_employed              2842
family_history                0
treatment                     1
Days_Indoors                  1
Growing_Stress                1
Changes_Habits                1
Mental_Health_History         1
Mood_Swings                   1
Coping_Struggles              1
Work_Interest                 1
Social_Weakness               1
mental_health_interview       1
care_options                  1
dtype: int64

In [ ]:
df['self_employed'].value_counts()

self_employed
No     130738
Yes     13316
Name: count, dtype: int64

In [ ]:
df['self_employed'].fillna("null", inplace= True)

In [ ]:
df.isnull().sum()

Timestamp                  0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  1
Days_Indoors               1
Growing_Stress             1
Changes_Habits             1
Mental_Health_History      1
Mood_Swings                1
Coping_Struggles           1
Work_Interest              1
Social_Weakness            1
mental_health_interview    1
care_options               1
dtype: int64

In [ ]:
df = df.dropna()
df.isnull().sum()

Timestamp                  0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  0
Days_Indoors               0
Growing_Stress             0
Changes_Habits             0
Mental_Health_History      0
Mood_Swings                0
Coping_Struggles           0
Work_Interest              0
Social_Weakness            0
mental_health_interview    0
care_options               0
dtype: int64

In [ ]:
df.describe()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
count,146896,146896,146896,146896,146896,146896,146895,146895,146895,146895,146895,146895,146895,146895,146895,146895,146895
unique,580,2,35,5,3,3,2,5,3,3,3,3,2,3,3,3,3
top,8/27/2014 11:43,Male,United States,Corporate,No,No,Yes,31-60 days,Yes,Yes,Maybe,Medium,No,Maybe,Maybe,No,No
freq,1204,94382,88995,31709,130738,82231,80182,32415,52298,54459,51098,51249,77453,52886,53578,120041,55743

In [ ]:
df.to_csv('Mental Health Dataset 1.csv', index= True )